version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: your-backend-image:latest  # Замените на ваш backend образ
    ports:
      - "8888:8888"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
